--ESPECIFICACION DEL OBJETO
CREATE OR REPLACE TYPE OBJECT_TATOO AS OBJECT(
       codigo                    NUMBER,
       nombre                    VARCHAR2(20),
       descripcion               VARCHAR2(150),
       ruta                      VARCHAR2(40),
       MEMBER PROCEDURE mostrar);

--CUERPO DEL OBJETO
CREATE OR REPLACE TYPE BODY OBJECT_TATOO AS
  MEMBER PROCEDURE mostrar IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Código: ' || codigo || ' - ' || 'nombre: ' || nombre ||' - ' || 'descripción: ' || descripcion);
  END;
END;

--TABLA CREADA A PARTIR DEL OBJETO INDICANDO LA LLAVE PRIMARIA
CREATE TABLE TATOOS of OBJECT_TATOO (PRIMARY KEY (codigo)); 
--INSERCIONES EN LA TABLA
INSERT INTO TATOOS VALUES(OBJECT_TATOO (1, 'Calavera', 'Calavera blanca en llamas','C://tatoos//calavera.png')); 
INSERT INTO TATOOS VALUES(OBJECT_TATOO (2, 'Dragon', 'Dragon estilo oriental','C://tatoos//dragon.png'));
--BLOQUE ANONIMO PARA LLAMAR EL METODO "MOSTRAR" DEL OBJETO
DECLARE
  mi_tatoo OBJECT_TATOO;
BEGIN
  SELECT VALUE(t) INTO mi_tatoo FROM TATOOS t WHERE t.codigo = 1;
  mi_tatoo.mostrar();
END;

--OBJETO PERSONA PARA HERENCIA
CREATE OR REPLACE TYPE TIPO_PERSON AS OBJECT(
       codigo                   NUMBER,
       dni                      NUMBER,
       nombre                   VARCHAR2(20),
       telefono                 NUMBER(10),
       tipo_dni                 VARCHAR2(1),
       genero                   VARCHAR2(1)
)
NOT INSTANTIABLE NOT FINAL;

--OBJETO CLIENTE HEREDADO DE PERSONA
CREATE OR REPLACE TYPE TIPO_CLIENTE UNDER TIPO_PERSON(
  Informacion VARCHAR2(250)
);

--TABLA DE CLIENTES
CREATE TABLE CLIENTES OF TIPO_CLIENTE(PRIMARY KEY (CODIGO),
CHECK (GENERO IN ('F'/*FEMENINO*/,'M'/*MASCULINO*/)AND GENERO = UPPER(GENERO)),
CHECK (TIPO_DNI IN ('C'/*CEDULA DE CIUDADANIA*/,'E'/*CEDULA EXTRANJERA*/,'T'/*TARJETA DE IDENTIDAD*/)AND TIPO_DNI = UPPER(TIPO_DNI)));

--INCERSION
INSERT INTO CLIENTES VALUES(TIPO_CLIENTE (1, 1049645321, 'Pedro Hernandez',3132567840,'C','M','Piel sensible')); 

--CONSULTA
select * from clientes;

--OBJETO EMPLEADO HEREDADO DE PERSONA
CREATE OR REPLACE TYPE TIPO_EMPLEADO UNDER TIPO_PERSON(
         NICK VARCHAR2(20),
         EMAIL VARCHAR2(40),
         RUTA_FOTO VARCHAR2(40)
)
NOT INSTANTIABLE NOT FINAL;
--TIPO TATUADOR QUE HEREDA DE EMPLEADO
CREATE OR REPLACE TYPE TIPO_TATOOARTIST UNDER TIPO_EMPLEADO(
         INFORMACION VARCHAR2(50)
);
--TABLA DE TATUADORES
CREATE TABLE TATOOARTISTS OF TIPO_TATOOARTIST(PRIMARY KEY (CODIGO),
CHECK (GENERO IN ('F'/*FEMENINO*/,'M'/*MASCULINO*/)AND GENERO = UPPER(GENERO)),
CHECK (TIPO_DNI IN ('C'/*CEDULA DE CIUDADANIA*/,'E'/*CEDULA EXTRANJERA*/,'T'/*TARJETA DE IDENTIDAD*/)AND TIPO_DNI = UPPER(TIPO_DNI)));

--INCERSION
INSERT INTO TATOOARTISTS VALUES(TIPO_TATOOARTIST (1, 1049645321, 'Pedro Hernandez',3132567840,'C','M','PELAO','PELAO@GMAIL.COM','C://TATUADORES//PELAO.PNG','CAMBIAR POR LA LISTA DE TRABAJOS')); 

--CONSULTA
SELECT * FROM TATOOARTISTS;

--=================CONTRACT==================
--ESPECIFICACION DEL OBJETO
CREATE OR REPLACE TYPE OBJECT_CONTRACT AS OBJECT(
       idContract                NUMBER,
       typeContract              VARCHAR2(1),
       descripcion               VARCHAR2(150),
       dateInitial               DATE,
       dateFinish                DATE,
       MEMBER PROCEDURE mostrar);
       
--CUERPO DEL OBJETO
CREATE OR REPLACE TYPE BODY OBJECT_CONTRACT AS
  MEMBER PROCEDURE mostrar IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Código: ' || idContract || ' - ' || 'Tipo de contrato: ' || typeContract ||' - ' || 'descripción: ' || descripcion 
                                  || 'Fecha de inicio: ' || dateInitial || ' - ' || 'Fecha final: ' || dateFinish);
  END;
END;  

--TABLA CREADA A PARTIR DEL OBJETO INDICANDO LA LLAVE PRIMARIA
CREATE TABLE CONTRACTS of OBJECT_CONTRACT (PRIMARY KEY (idContract),
CHECK (typeContract IN ('F'/*TERMINO FIJO*/,'I'/*TERMINO INDEFINIDO*/,'S'/*PRESTACION DE SERVICIOS*/)AND typeContract = UPPER(typeContract))); 

--INSERCIONES EN LA TABLA
INSERT INTO CONTRACTS VALUES(OBJECT_CONTRACT (1, 'F', 'contrato a termino fijo',TO_DATE('2017/01/01','yyyy/mm/dd'), TO_DATE('2020-01-01','yyyy/mm/dd'))); 
INSERT INTO CONTRACTS VALUES(OBJECT_CONTRACT (2, 'I', 'contrato a termino indefinido',TO_DATE('2017/01/01','yyyy/mm/dd'), NULL)); 
--BLOQUE ANONIMO PARA LLAMAR EL METODO "MOSTRAR" DEL OBJETO
DECLARE
  mi_contract OBJECT_CONTRACT;
BEGIN
  SELECT VALUE(t) INTO mi_contract FROM CONTRACTS t WHERE t.idContract = 1;
  mi_contract.mostrar();
END;






CREATE OR REPLACE TABLE PAYMENT
(
       CODIGO           NUMBER NOT NULL,
       FECHA            TIMESTAMP NOT NULL,
       PAGO             DECIMAL NOT NULL
)
ALTER TABLE PAYMENT ADD(
      CONSTRAINT PK_PAYMENT PRIMARY KEY (CODIGO)
)

CREATE OR REPLACE TABLE APPOINMENT
(
       CODIGO                  NUMBER NOT NULL,
       FECHA_ASIGNACION        TIMESTAMP NOT NULL,
       FECHA_CITA              TIMESTAMP NOT NULL
)
ALTER TABLE APPOINMENT ADD(
      CONSTRAINT PK_APPOINMENT PRIMARY KEY (CODIGO)
)

CREATE OR REPLACE TABLE TATOOWORK 
(
       CODIGO                  NUMBER NOT NULL,
       COSTO_TOTAL             DECIMAL NOT NULL
)

ALTER TABLE TATOOWORK ADD(
      CONSTRAINT PK_TATOOWORK PRIMARY KEY (CODIGO)
)



